# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: gl:openscm/copier-basic-python-repository
email: zebedee.nicholls@climate-energy-college.org
name: Zebedee Nicholls
notebooks: true
package_manager: uv
project_description_short: Application of the CMIP branded variable mapper to the
    CMIP7 data request
project_url: https://github.com/znicholls/CMIP7-Data-Request-Branded-Variables
